### ISSUE TITLE
Hubspot Integration: Add activityType in Engagements

### ISSUE THREAD

**Issue by danbradford** [stitchdata/docs#812] opened 2022-09-14 16:51 UTC
There is a field in Hubspot Engagements called activityType that is not currently included in the Stitch ETL. Can that be add in? Should just be a minor change to the engagements.json file.

[tap-hubspot](https://github.com/singer-io/tap-hubspot)/[tap_hubspot](https://github.com/singer-io/tap-hubspot/tree/master/tap_hubspot)/[schemas](https://github.com/singer-io/tap-hubspot/tree/master/tap_hubspot/schemas)/engagements.json

**Comment by lmilan** [comment] 2022-10-10 08:04
Hi, I'm closing this since it's a duplicate of the issue in the tap-hubspot repository (https://github.com/singer-io/tap-hubspot/issues/207)

**Closed by lmilan** 2022-10-10 08:04 UTC
